name: Publish Python distributions to PyPI and TestPyPI

# Trigger on workflow_dispatch (manual), and when a release is published
on:
  workflow_dispatch:  # Manual trigger
  release:
    types: [published]  # Trigger when a release is published

jobs:
  python-build-n-publish:
    name: Build and publish Python distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main  # Checks out your repository

      - name: Initialize Python 3.9
        uses: actions/setup-python@v3  # Use the latest version
        with:
          python-version: 3.9  # Or your preferred version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
     
      - name: Lint with flake8
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      
      - name: Build binary wheel and a source tarball
        run: |
          python setup.py sdist
          python setup.py bdist_wheel  # Create binary wheel
      
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.pypi_password }}  # Change to your PyPI password secret
          repository_url: https://upload.pypi.org/legacy/  # URL for PyPI
